#!/usr/bin/env bash
#Setting up a firewall to allow only incoming traffic on ports 80, 443, and 22
sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 443/tcp
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw enable 
sudo ufw status
