#!/usr/bin/env bash
# Install Nginx and configure custom HTTP response header

# Install Nginx
apt-get update
apt-get -y install nginx

# Configure Nginx
echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/nginx.conf > /dev/null
sudo service nginx restart
