#!/usr/bin/env bash
# Install HAproxy
sudo apt update -y
sudo apt install haproxy -y

# Configure HAproxy to send traffic to web-01 and web-02 using roundrobin algorithm
config="\
backend my_servers
    balance roundrobin
    server 5429-web-01 34.207.252.153:80 check 
    server 5429-web-02 54.210.60.201:80 check

frontend haproxy_inbound
    bind *:80
    default_backend my_servers
    mode http
"

sudo bash -c "echo '$config' > /etc/haproxy/haproxy.cfg"

# Enable and start the HAproxy service
sudo systemctl enable haproxy
sudo systemctl start haproxy

# Update /etc/hosts file with the correct hostnames
sudo bash -c "echo '34.207.252.153 5429-web-01' >> /etc/hosts"
sudo bash -c "echo '54.210.60.201 5429-web-02' >> /etc/hosts"
