#!/usr/bin/env bash
# Update the package list

sudo apt-get update

# Install nginx
sudo apt-get install nginx -y

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80 default_server/listen 80/g' /etc/nginx/sites-available/default

# Configure redirection
echo "
server {
    listen 80;
    listen [::]:80;

    server_name jkarenzi.tech;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # rest of server configuration
}
" | sudo tee /etc/nginx/sites-available/example.com >/dev/null

# Enable the site
sudo ln -s /etc/nginx/sites-available/example.com /etc/nginx/sites-enabled/

# Remove the default site symlink
sudo rm /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart
