#!/usr/bin/env bash
#A bash script that installs Nginx web server and configures it with a custom 404 page

apt-get update
apt-get install -y nginx

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

printf %s "server {
listen 80 default_server;
listen [::]:80 default_server;
root /var/www/html;
index index.html index.htm;
error_page 404 /404.html;
location = /404.html {
internal;
}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
